In [9]:
print('Введите числа: ', end='')
number = int(input())
sum = number
squares = number ** 2
while sum != 0:
    number = int(input('> '))
    sum += number
    squares += number ** 2
print(squares)

Введите числа: 2


In [10]:
n = int(input('Введите число: '))
if n < 0:
    print('Число должно быть неотрицательным!')
result = []
i = 1
while len(result) < n:
    for _ in range(i):
        result.append(i)
    i += 1
print(result)

[1, 2, 2, 3, 3, 3, 4, 4, 4, 4]


In [13]:
import numpy as np

matrix = np.random.randint(10, size=(3, 3))
print('Исходная матрица:')
print(matrix)
vector = []
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        vector.append(matrix[i][j])
print('Полученный вектор: ', vector)

Исходная матрица:
[[3 7 8]
 [8 1 0]
 [6 8 9]]
Полученный вектор:  [3, 7, 8, 8, 1, 0, 6, 8, 9]


In [14]:
a = [1, 2, 3, 4, 2, 1, 3, 4, 5, 6, 5, 4, 3, 2]
b = ['a', 'b', 'c', 'c', 'c', 'b', 'a', 'c', 'a', 'a', 'b', 'c', 'b', 'a']
result = dict()
for i in range(len(b)):
    if b[i] in result:
        result[b[i]] += a[i]
    else:
        result[b[i]] = a[i]
print(result)

{'a': 17, 'b': 11, 'c': 17}


In [2]:
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing(as_frame=True)

In [15]:
import pandas as pd

pd.concat([data, data['target']], axis=1)
pd.concat([data, data['target_names']], axis=1)

TypeError: cannot concatenate object of type '<class 'sklearn.utils.Bunch'>'; only Series and DataFrame objs are valid