In [2]:
print('Введите числа: ', end='')
number = int(input())
sum = number
squares = number ** 2
while sum != 0:
    number = int(input('> '))
    sum += number
    squares += number ** 2
print(squares)

Введите числа: 150


In [8]:
n = int(input('Введите число: '))
if n < 0:
    print('Число должно быть неотрицательным!')
result = []
i = 1
while len(result) < n:
    for _ in range(i):
        if len(result) + 1 > n:
            break
        result.append(i)
    i += 1
print(result)

[1, 2, 2, 3, 3, 3, 4, 4]


In [13]:
import numpy as np

matrix = np.random.randint(10, size=(3, 3))
print('Исходная матрица:')
print(matrix)
vector = []
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        vector.append(matrix[i][j])
print('Полученный вектор: ', vector)

Исходная матрица:
[[3 7 8]
 [8 1 0]
 [6 8 9]]
Полученный вектор:  [3, 7, 8, 8, 1, 0, 6, 8, 9]


In [14]:
a = [1, 2, 3, 4, 2, 1, 3, 4, 5, 6, 5, 4, 3, 2]
b = ['a', 'b', 'c', 'c', 'c', 'b', 'a', 'c', 'a', 'a', 'b', 'c', 'b', 'a']
result = dict()
for i in range(len(b)):
    if b[i] in result:
        result[b[i]] += a[i]
    else:
        result[b[i]] = a[i]
print(result)

{'a': 17, 'b': 11, 'c': 17}


In [5]:
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing(as_frame=True)

In [6]:
import pandas as pd

pd.concat([data['data'], data['target']], axis=1)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

In [17]:
data['data'].info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB


In [18]:
data['data'].isna().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [41]:
data['data'].loc[(data['data']['HouseAge'] > 50) & (data['data']['Population'] > 2500)]

MedInc  HouseAge  AveRooms  AveBedrms  Population    AveOccup  \
460    1.4012      52.0  3.105714   1.060000      3337.0    9.534286   
4131   3.5349      52.0  4.646119   1.047945      2589.0    5.910959   
4440   2.6806      52.0  4.806283   1.057592      3062.0    4.007853   
5986   1.8750      52.0  4.500000   1.206349      2688.0   21.333333   
7369   3.1901      52.0  4.730942   1.017937      3731.0    4.182735   
8227   2.3305      52.0  3.488860   1.170380      3018.0    3.955439   
13034  6.1359      52.0  8.275862   1.517241      6675.0  230.172414   
15634  1.8295      52.0  2.628169   1.053521      2957.0    4.164789   
15652  0.9000      52.0  2.237474   1.053535      3260.0    2.237474   
15657  2.5166      52.0  2.839075   1.184049      3436.0    1.621520   
15659  1.7240      52.0  2.278566   1.082348      4518.0    1.780142   
15795  2.5755      52.0  3.402576   1.058776      2619.0    2.108696   
15868  2.8135      52.0  4.584329   1.041169      2987.0    3.966799   

       Latitude  Longitude  
460       37.87    -122.26  
4131      34.13    -118.20  
4440      34.08    -118.21  
5986      34.10    -117.71  
7369      33.97    -118.21  
8227      33.78    -118.20  
13034     38.69    -121.15  
15634     37.80    -122.41  
15652     37.80    -122.41  
15657     37.79    -122.41  
15659     37.79    -122.41  
15795     37.77    -122.42  
15868     37.76    -122.41

In [48]:
data['target'].max()

5.00001

In [49]:
data['target'].min()

0.14999

In [54]:
data['data'].apply(pd.DataFrame.mean)

MedInc           3.870671
HouseAge        28.639486
AveRooms         5.429000
AveBedrms        1.096675
Population    1425.476744
AveOccup         3.070655
Latitude        35.631861
Longitude     -119.569704
dtype: float64